### ISSUE TITLE
LOB SDK INTEGRATION ISSUE

### ISSUE THREAD

**Issue by riksof-abdulrauf** [lob/lob-ios#12]
I am integrating new wrapper of lob, facing issues while integration, I followed the steps mentioned on bellow links

https://github.com/lob/lob-ios
http://stackoverflow.com/questions/9370518/xcode-4-2-how-include-one-project-into-another-one

Didn't get any success, right now I am facing following issue, please check attached image.
![screen shot 2015-03-16 at 7 12 14 pm](https://cloud.githubusercontent.com/assets/5626513/6669020/912b00aa-cc18-11e4-8b5f-80ca1c9ecc88.png)

**Comment by mgartner** [comment]
Here is a description of the fix from @riksof-abdulrauf: http://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64/29098922#29098922

**Comment by pon** [comment]
Closing since solution provided
