### ISSUE TITLE
Update of API version 2015-06-25 required any code change ?

### ISSUE THREAD

**Issue by riksof-abdulrauf** [lob/lob-ios#13]
Update of API version 2015-06-25 required any code change ?
I am using the library of iOs
https://github.com/lob/lob-ios

**Comment by mgartner** [comment]
This wrapper is not officially supported. You may be able to get it working with the latest version of the API, however.

I'm more than happy helping you integrate with Lob using another wrapper, ideally on the server-side of your application.

**Comment by riksof-abdulrauf** [comment]
@mgartner : its working fine with my testing a/c. But causing error for live account.
Both using same piece of code and same version.

Error is:
Printing description of error:
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo=0x1704fa800 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17463e4c0> { URL: https://api.lob.com/v1/objects } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 11 Aug 2015 16:40:19 GMT";
    "Transfer-Encoding" = Identity;
    Vary = "origin,accept-encoding";
    "access-control-allow-credentials" = true;
    "access-control-allow-headers" = "Authorization, Content-Type, If-None-Match";
    "access-control-allow-methods" = "GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS";
    "access-control-expose-headers" = "WWW-Authenticate, Server-Authorization";
    "access-control-max-age" = 86400;
} }, NSErrorFailingURLKey=https://api.lob.com/v1/objects, com.alamofire.serialization.response.error.data=<7b0a2020 20202265 72726f72 223a207b 0a202020 20202020 20226d65 73736167 65223a20 226e616d 65206973 206e6f74 20616c6c 6f776564 222c0a20 20202020 20202022 73746174 75735f63 6f646522 3a203432 320a2020 20207d0a 7d>, NSLocalizedDescription=Request failed: client error (422)}

**Comment by msencenb** [comment]
Is there a mailing list we can get on that announces deprecations like this? I wasn't aware that this wrapper was no longer supported, and it's still actively being used. I'm happy to update my app, but it sucks that this is the first time I'm hearing about support being dropped for this.

**Comment by mgartner** [comment]
Sorry for the abruptness of this message. We will continue to support users who have been using the iOS wrapper, but we don't suggest new users to integrate with iOS, and I wanted to make that clear. We'll do our best to make sure everything still works for existing users, but we cannot guarantee that all new features released in the API will work with the iOS wrapper.

**Comment by msencenb** [comment]
Fair enough, thanks for the update!
