### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by graysonc** [lob/lob-ios#7]
>...
>we are getting HTTP error code 422. And in the response handler (in bold below) the error object is >nil, while the postcard object is not nil. However, all data inside the postcard object is nil. 

```
    NSDictionary *postcardDict = @{@"name" : @"Demo Postcard",
                                   @"front" : @"https://www.lob.com/postcardfront.pdf",
                                   @"back" : @"https://www.lob.com/postcardback.pdf",
                                   @"to" : Test_Address_Harry,
                                   @"from" : Test_Address_Harry};
    
    LobPostcardModel *postcardModel = [LobPostcardModel initWithDictionary:postcardDict];
    
    request = [[LobRequest alloc] initWithAPIKey:testApiKey];
    
    [request createPostcardWithModel:postcardModel
                        withResponse:^(LobPostcardModel *postcard, NSError *error)
     {
         NSLog(@"*** Postcard Create Response ***");
         
         NSLog(@"%u", request.statusCode);

     }];
    
    return;
```

**Comment by msencenb** [comment]
Any updates on this, I'm facing the same 422 bug when attempting to integrate lob. It appears to be a problem with the authorization headers. In LobRequest.m:

- (void)addAuthorizationToRequest:(NSMutableURLRequest * )request

self.apiKey is equal to my key plus two colons at the end of it "::", which seems to be adding extra base64 encoded data. Oddly the address verification succeeds with this authorization header (and dropping all the colons causes it to fail), but the postcard creation is still barfing on it.

**Comment by riksof-abdulrauf** [comment]
Thanks @pon , My issue was solved,

@msencenb can you elaborate how are you integrating LOB, I wish I could help you.

**Comment by riksof-abdulrauf** [comment]
Hi @pon I need your support, have you guys made any change in lob code/Api ?
The code I have implemented for lop post card was working [2014/12/12] , right now I am testing the old build [ code ] its giving me the 422 error.

Please let me how can i fix it.

Error is coming when I am creating object [exporting file from device ].
Code I am using,

     filePath  =   [self exportFlyer];
        objectDict = @{
                       @"name" : @"Flyer Postcard",
                       @"setting" : @{@"id" : @"200"},
                       @"file" : filePath
                     };
    
    
    LobObjectModel *objectModel = [LobObjectModel initWithDictionary:objectDict];
    
    if( !([filePath isEqualToString:@""]) ) {
        objectModel.localFilePath = YES;
    }
    
    [request createObjectWithModel:objectModel
                      withResponse:^(LobObjectModel *object, NSError *error)
     {
         NSLog(@"*** Object Create Local Response *** %ld", (long)request.statusCode);

**Comment by pon** [comment]
Closing out this issue - I think it's become too generic. Feel free to open another issue with the specific issue or reach out to support@lob.com with anything questions.
